---
title: "DZ2"
author: "Eleonora Detić"
date: "11/1/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Zadatak 3 - Cijena dionice

## a dio
```{r}
#grafičko testiranje ovisnosti
dionica = read.csv("dionica.csv") #učitavanje podataka
par(mfrow=c(2,2)) 
plot(dionica$BDP, dionica$Cijena, col="red") # uopće se ne čini zavisnos
plot(dionica$ZAP, dionica$Cijena, col="blue") #moguća zavisnost
plot(dionica$KS, dionica$Cijena, col="green")
plot(dionica$MJ, dionica$Cijena, col= "orange") #moguća zavisnost

#testiranje ovisnosti kroz model
model = lm(dionica$Cijena ~ dionica$BDP+dionica$ZAP+dionica$KS+dionica$MJ)
summary(model) 
#mali p value - model statisticki značajan
#ZAP zavisan najviše, MJ nakon njega, BDP nije tolko važan za cijenu
```
## b dio
```{r}
#pouzdana pruga za srednju vrijednost
plot(dionica$Cijena)
matrica = predict(model, level=0.9, i="c") 
matrica = as.data.frame(matrica)
plot(dionica$Cijena)
lines(matrica$lwr, col="red") 
lines(matrica$upr, col="red")
```
## c dio
```{r}
#testiranje da je koeficijent uz kamatna stopu 100
model2 = lm(dionica$Cijena ~dionica$BDP+dionica$ZAP+ offset(100*dionica$KS)+dionica$MJ) 
anova(model2,model)
#velika p vrijednost -> jednostavniji model(model2) je "dovoljan"
#ne odbacujemo nul hipotezu, znaci da je ovaj koeficijent 100
#ne postoji statisticki znacajna razlika izmedu modela
confint(model, level=0.95) #100 je u KS
```

## d dio
```{r}
nova_cijena = read.csv("nova_cijena.csv") 
model = lm(Cijena~BDP+ZAP+KS+MJ,data=dionica) #model od prije 

x = data.frame(BDP=nova_cijena$BDP,ZAP=nova_cijena$ZAP,KS=nova_cijena$KS,MJ=nova_cijena$MJ)
predikcije = predict(model,x,level=0.9,i="p")
predikcije
#starim modelom predviđamo za nove vrijednosti

#Nacrtajmo intervale i opazene tocke
plot(nova_cijena$Cijena,xlim=c(0,12),ylim=c(500,1500))
x = c(1:length(nova_cijena$Cijena))
points(x,predikcije[,2],type="l",col="red") #donja granica za opazanje
points(x,predikcije[,3],type="l",col="red") #gornja granica za opazanje
#nije dobar predikcijski model jer mi 3/12 =25% točaka ispada van
#mali broj uzorka
```

## e dio
```{r}
#uklananje točaka radi poboljšanja prediktivne vrijednosti
library(base)
distance = cooks.distance(model)
length(distance[distance > 0.5]) 

#utjecajne točke ne postoje
```


### Zadatak 4

## a dio
```{r}
prodaja = read.table("prodaja.dat", header=TRUE) 
model = lm(prodaja$kolicina~prodaja$dan)
summary(model) #dobar model
plot(prodaja$dan, prodaja$kolicina, col="blue")
lines(model$fitted.values, col="red")
#neki logaritimarski podaci
```

## b dio - provjera pretpostavki linearnog modela
```{r}
#1.linearnost podataka
res = model$res
plot(model$fitted.values, res) 
abline(a=0,b=0)
#raspršenje oko apcise ukazuje na nelinearnost
plot(prodaja$kolicina, predict(model),xlim=c(4,8), ylim=c(5,7))
abline(a=0,b=1, col="red")
#raspršenje oko pravca y=x ukazuje na nelinearnost

#možda dodati pretpostavke i prije??

plot(prodaja$dan, prodaja$kolicina)
plot(prodaja$dan, exp(prodaja$kolicina)) #vidimo da je ovo dobra transformacija
model = lm(exp(prodaja$kolicina)~prodaja$dan)
summary(model)

#2.nezavisnost grešaka
library(lmtest)
#dodaj qqnorm
dwtest(model)
#null hipoteza je da ne postoji korelacija
#velik p vrijednost, ne odbacujemo null hipotezu 
#možemo pretpo da na svakoj stan raz značajnosti nisu korelirani
#nekoreliranost povlaci nezavisnost

#3. homogenost greška
library(tseries)
jarque.bera.test(model$res)
#mala p value, odbacujemo H_0, 
#null hipoteza je podaci dolaze iz normalne distribucije
#ovi rezidualni nisu normali


#4. normalnost greška
shapiro.test(model$res)
#mala p value, odbacujemo H_0
#nemogu pretpo normalnost
```

## c dio
```{r}
y <- exp(prodaja$kolicina)
x <- prodaja$dan
model = lm(y ~ x)
future <- data.frame(x = c(1096:1102))

plot(log(predict(model, newdata = future, interval = 'confidence'))[,1], xlim=c(0,10), ylim=c(6.7,6.8), ylab="kolicina prodaje")
lines(log(predict(model, newdata = future, interval = 'confidence')[,2]), col="red") 
lines(log(predict(model, newdata = future, interval = 'confidence')[,3]), col="red")

predict(model, newdata = future, interval = 'confidence',level=0.9)
predict(model, newdata = future, interval = 'confidence')
```












