---
title: "DZ3"
author: "Eleonora Detić"
date: "12/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Zadatak 5 - Auto osiguranje

## a dio
```{r}
#prosječan iznos prijavljene štete po spolu
auto <- read.csv("auto.csv")
aggregate(auto$iznos, list(auto$spol), FUN=mean) 
```

## b dio
```{r}
#ispitivanje statističke povezanosti varijable prijava o spolu i županiji
#grafički
zupanija = aggregate(auto$prijava, list(auto$zupanija, auto$prijava), FUN=length)
barplot(matrix(zupanija$x,ncol = 21,byrow = TRUE), beside=T, legend =  c('Nisu prijavili štetu','Prijavili su štetu'), names.arg = c(1:21), col=c('blue', 'gray'))
spol = aggregate(auto$prijava, list(auto$spol,auto$prijava), FUN=length) 
barplot(matrix(spol$x,ncol = 2,byrow = TRUE), beside=T, legend = c('Nisu prijavili štetu','Prijavili su štetu'), names.arg = c("Muškarci", "Žene"), col=c('pink', 'gray'))


#ineferencijalno
library(DescTools)
#hi kvadrat test H_0 -> nezavisne su 
chisq.test(auto$prijava, auto$spol) #mali p vrijednost, odbacujem H_0
chisq.test(auto$prijava, auto$zupanija) #velik p vrijednost, ne odbacujemo H_0 

CramerV(auto$prijava, auto$spol) #manji od 0.1 - nema povezanosti
CramerV(auto$prijava, auto$zupanija) #manji od 0.1 - nema povezanosti
#vise utjece zupanija jer ima veci C. koeficijent
```

## c dio
```{r}
#ispitivanje linearne povezanosti dobi i duljine vozačkog iskustva -> obje gledamo kao neprekidne

#grafički
#plot(auto$dob, auto$iskustvo, col="blue") 
library(ggplot2)
library(ggpubr)
ggscatter(auto, x = "dob", y = "iskustvo", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Miles/(US) gallon", ylab = "Weight (1000 lbs)")+theme_bw()
#ovaj grafički prikaz mi već djeluje kao da bi mogle biti jako zavisne


#inefercijalno
cor(auto$dob,auto$iskustvo,method="spearman") #0.9952043
cor(auto$dob,auto$iskustvo,method="pearson") #0.9969117
#koeficijenti blizu 1, jako zavisne, nebi smjele ići zajedno u model!

```
## d dio
```{r}
#ispitivanje ovisnosti iznosa štete i dobi - ovisi li to o prijavi štete? 

model1 <- lm(auto$iznos ~ auto$dob)
summary(model1) 
#kod manjih iznosa šteta dob nije bitna, a kod većih se poveća kao što se poveća i dob

col<-c("pink", "blue")[factor(auto$prijava)]
plot(auto$dob,auto$iznos,xlab="Dob",ylab="Iznos",pch=4,col=col)
#gornji dio se ponaša linearno,a donji ne
abline(300000,0,col="red",lwd=4) #odvojam dio koji je linearni i onaj koji nije

plot(auto$dob[auto$iznos>300000 & auto$prijava == 0], auto$iznos[auto$iznos>300000 & auto$prijava == 0],col="red")
plot(auto$dob[auto$iznos>300000 & auto$prijava == 1], auto$iznos[auto$iznos>300000 & auto$prijava == 1],col="blue")
#i kod onih koji su prijavili i nisu prijavili vidimo linearan odnos za iznose štete veće od 30000

#posebno dva modela ovisno o prijavu
model_0=lm(auto$iznos[auto$iznos>300000 & auto$prijava == 0] ~ auto$dob[auto$iznos>300000 & auto$prijava == 0])
summary(model_0)
model_1=lm(auto$iznos[auto$iznos>300000 & auto$prijava == 1] ~ auto$dob[auto$iznos>300000 & auto$prijava == 1])
summary(model_1)

#predikcije svakog od modela
plot(auto$dob[auto$iznos>300000 & auto$prijava == 0], auto$iznos[auto$iznos>300000 & auto$prijava == 0],col="red")
lines(auto$dob[auto$iznos>300000 & auto$prijava == 0],model_0$fitted.values)
plot(auto$dob[auto$iznos>300000 & auto$prijava == 1], auto$iznos[auto$iznos>300000 & auto$prijava == 1],col="blue")
lines(auto$dob[auto$iznos>300000 & auto$prijava == 1], model_1$fitted.values)
#procjene su otprilike iste bilo osoba imala prijavu ili ne pa cini nam se da interakcija neće imat ulogu

model2 <- lm(auto$iznos ~ auto$dob * factor(auto$prijava)) #dodavanje interekacije
summary(model2) #ovdje ispada da interakcija nije znacajna

anova(model1,model2) #velik p value, dovoljan je jednostavan model -> interakcija nije stat značajna kao što smo vidjeli i gore
#taj omjer ne ovisi o tome je li osoba vec prijavila stetu ili ne 

#grafički prikazi 
interaction.plot(x.factor=auto$dob, trace.factor = auto$prijava, response = auto$iznos,col = c("red", "blue"), trace.label = "Prijava", type = "p",pch=c(0:1))

#text(auto$dob,auto$iznos,as.character(auto$prijava)) #mogu i ovo ali mi je malo nepregledno
lapply(split(auto,auto$prijava),summary) #deskriptivna statistika za prijavu

#prikaz modela
plot(auto$dob[auto$iznos>300000],auto$iznos[auto$iznos>300000],xlab="Dob",ylab="Iznos")
library(ggplot2)
auto_new = data.frame(auto$dob[auto$iznos>300000],auto$iznos[auto$iznos>300000])
auto_new.names()
names(auto_new)
ggplot(auto_new, aes(x = auto.dob.auto.iznos...3e.05., y = auto.iznos.auto.iznos...3e.05.)) + geom_point() +stat_smooth(method = "lm", col = "red")
#model ima smisla ako je steta veca od 30000
```

## e dio
```{r}
#odabir optimalnog modela bez interakcija
model_full = lm(auto$iznos ~ auto$spol + auto$zupanija + auto$dob + auto$iskustvo + auto$br.uzdr.cl + auto$udio.stete + auto$prijava)
step(model_full,trace=T)
#najbolji model je onaj najdonji, tamo je AIC kriterij najmanji
#iznos = intercept + spol + iskustvo + udio_stete
```

## f dio
```{r}
#uvođenje varijabla u model obrnutim redoslijedom
model <- lm(auto$iznos ~ 1)
summary(model)  #samo intercept je u modelu
step(model,trace=T, direction = "forward",scope=formula(model_full))
#ponovo čitamo skroz na kraju -> dobili smo isti model
```
## g dio

```{r}
#uvodimo sve varijable osim vozačkog iskustva i ponavljamo dio sa step
model_no_experience = lm(auto$iznos ~ auto$spol + as.factor(auto$zupanija) + auto$dob + auto$br.uzdr.cl + auto$udio.stete + as.factor(auto$prijava))
summary(model_no_experience) #značajan model

step(model_no_experience) #ponavljamo dio od prije
#optimalni model sada ovisi o spolu, dobi i udiu stete   
#model nije isti jer smo izbacili iskustvo koja je važna varijabla po AIC kriteriju
```


## Zadatak 6 - Zaraza koronavirusom

## a dio
```{r}
korona <- read.csv("korona_hrv.csv",header=FALSE) 
#plot( c(1:153),korona$V1)
ts.plot(korona, col="red")
ts.plot(korona$V1[100:120], col="red") #izdvojen jedan segmentic - period je 7

#nije homogeno, vidimo sve veći porast u broju zarazenih kroz vrijeme
#moguća homogenost do tipa indeksa 75, nakon toga veliki skokovi pa nemamo više homogenost
#ako je homogeno onda se ne mijenja varijanca i ocekivanja na podskupovima podataka
```

## b dio
```{r}
xt = ts(korona$V1, frequency = 7)
x.stl=stl(xt,s.window = "periodic")
plot.ts(xt, col="red", main="Podaci prije transformacije")
plot(x.stl,col="red", main="STL prije transofrmacije")
#uočavamo eksponencijalni trend, pa ćemo logaritmirati podatke

xt = log(xt)
x.stl=stl(xt,s.window = "periodic")
plot.ts(xt, col="blue", main="Podaci nakon logaritmiranja")
plot(x.stl,col="blue", main="STL nakon logaritmiranja")


x_no_sez = xt -x.stl$time.series[,1]
plot.ts(x_no_sez,col="green",main="Desezonalni niz") #uklananje sezonalnosti
x_no_trend = x_no_sez -x.stl$time.series[,2] #uklanjanje trenda
plot.ts(x_no_trend,col="green",main="Desezonalni niz sa uklonjenim trendom")

acf(x.stl$time.series[,3])
#5 stupića odskače od 23, što je više od 5% pa nemožemo pretpostaviti nekoreliranost
library('nortest')
lillie.test(x.stl$time.series[,3])#mala p vrijednost, ostaci nisu normalni - nemamo bijeli šum

```


## c dio
```{r}
xt = ts(korona$V1, frequency = 7)
xt_new = log(xt)
x_new_stl =stl(xt_new ,s.window = "periodic")
pacf(x_new_stl$time.series[,3]) 
acf(x_new_stl$time.series[,3]) #skok nakon 4 stupica - AR(4)

#MA(1) = arima(0,0,1)
#AR(1) = arima(1,0,0)
#fitamo MA proces

AR_1 <- arima(x_no_sez, order = c(4,0,0),include.mean = T, d=1) #ovo javlja gresku jer nije stacionarno, moramo diferencirati
xt_diff <- diff(x_no_sez)

AR_1 <- arima(xt_diff,order = c(4,0,0)) #sad je okej, AIC je -18.32

  
#isprobavanje AR modela za fit
arima(xt_diff,order = c(1,0,0)) #AR(1) aic je -6
arima(xt_diff,order = c(2,0,0)) #AR(2) aic je -13
arima(xt_diff,order = c(3,0,0)) #AR(1) aic je -19
arima(xt_diff,order = c(4,0,0)) #AR(1) aic je -18
arima(xt_diff,order = c(5,0,0)) #AR(1) aic je -17

#isprobavanje MA modela za fit
arima(xt_diff,order = c(0,0,1)) #MA(1) aic je -19
arima(xt_diff,order = c(0,0,2)) #MA(2) aic je -17
arima(xt_diff,order = c(0,0,3)) #MA(3) aic je -16
arima(xt_diff,order = c(0,0,4)) #MA(1) aic je -24
arima(xt_diff,order = c(0,0,5)) #MA(1) aic je -22
arima(xt_diff,order = c(0,0,6)) #MA(1) aic je -29
#6 nam je okej, dalje se povećava

MA_final = arima(xt_diff,order = c(0,0,6)) # za taj model smo se odlucili
acf(MA_final$residuals) #svi su unutra, nekolireni -> to nam se sviđa
library('nortest')
lillie.test(MA_final$residuals) #nije bas normalno al skoro je .. :) 

future <- predict(MA_final , n.ahead = 24)$pred
future_se <- predict(MA_final , n.ahead = 24)$se


#grafički prikaz procjena
ts.plot(xt_diff,xlim=c(0,40))
points(future, type = "l")
points(future - 2*future_se, type = "l", col = 2, lty = 2)
points(future + 2*future_se, type = "l", col = 2, lty = 2)


#koliko su naše procjene blizu?
new_korona <- read.csv("korona_hrv_studeni.csv",header=FALSE)
razlika = exp(AR_forecast) - new_korona$V1
razlika
 AR_forecast
```

##provjera

```{r}




library(forecast)
auto.arima(diff(xt_transform))



xt = ts(korona$V1, frequency = 7)
plot.ts(xt)
plot.ts(log(xt)) #vidimo da se varijanca malo stabilizirala
xt_transform = log(xt)
library(forecast)
auto.arima(diff(xt_transform))
#7 je period (1,0,0) je sezonalni dio(2,1,0), najbolji fit je ARIMA(2,1,2)


fit <- arima(xt_transform, c(2, 1, 2), seasonal = list(order = c(2, 1, 0), period = 7))
acf(fit$residuals) #nisu nekorelirani



AR_fit <- predict(fit, n.ahead = 24)$pred
AR_fit_se <- predict(fit, n.ahead = 24)$se
razlike = AR_fit+AR_fit_se - new_korona$V1
razlike
new_korona$V1
AR_fit
diffinv(AR_fit)
```



## Zadatak 7 - podaci o proizvodnji električne opreme

## a dio 
```{r}
electric <- read.table("electric.txt")
electric <- ts(electric$V1,frequency = 12)
ts.plot(electric, col="red")
#procjena sezonalnosti metodom pomicnih zareza
# d=12, q=6
#prvih 6 tocaka i zadnjih 6 nema procjenu, sve ostale imaju
tmp = c(1/24, 1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/24)

matrix(electric[6:(length(electric)-6)] * tmp,ncol=12, byrow=T)
outer(electric[6:(length(electric)-6)],tmp)
mt = rowSums(outer(electric[6:(length(electric)-6)],tmp))
mt

M = matrix(electric[7:(length(electric)-7)],ncol=12,byrow=TRUE) - matrix(mt,ncol=12,byrow=TRUE) #svi s indeksom 1 su u prvom stupcu
wk = colMeans(M)
sk = wk - mean(wk)

x.stl = stl(electric,s.window="periodic")
x.stl$time.series[,1][1:12] #procjena sezonalnosti gotovom metodom
plot(c(1:12), x.stl$time.series[,1][1:12],ylim=c(-15,15))
points(sk,col="red") #crveno su moje procjene
#a <- c(1:3)
#b <- c(1:4)
#outer(a,b) #svaki iz a je pomnožen sa svakim iz b

plot(x.stl)
#pogodan model za trend
ts.plot(electric)
lines(x.stl$time.series[,2],col="red")
#analiza ostataka
acf(x.stl$time.series[,3])
#neznam jel ovo bijeli sum il ne jer kao ove crtice nebi smjele ispadati?


```


## b dio
```{r}
#analiza podataka bez trenda i nalazak ARIMA procesa
fit <- Arima(electric, order=c(1,0,0))
checkresiduals(fit)
```





























